[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]
resolver = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
